

spring.datasource.url=jdbc:mysql://localhost:3306/interior?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true


spring.datasource.username=root


spring.datasource.password=M@1977@nasa$

# The translator that connects Java to MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

    # ==========================================
    # JPA / HIBERNATE SETTINGS
    # ==========================================

# Hibernate reads your Java entities and maps them to existing tables
# "update" means: don't delete data, just update the structure if needed
spring.jpa.hibernate.ddl-auto=update

# Makes MySQL the language Hibernate speaks
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Prints every SQL query in the console (great for learning/debugging!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# APP SETTINGS
# ==========================================

# Your app will run on this port ? React will talk to this
server.port=8080